// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu_jYgcJaPiHKe0Q7ujCczxsMHsZQBs2E',
    appId: '1:347814344271:web:ea28b38f84a6a26f6b1c3a',
    messagingSenderId: '347814344271',
    projectId: 'speechtotextapp-46ef3',
    authDomain: 'speechtotextapp-46ef3.firebaseapp.com',
    storageBucket: 'speechtotextapp-46ef3.appspot.com',
    measurementId: 'G-PHL7D2Y513',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs8dxPqSdgY-3QZyhRmG7LUc8qaiQM50k',
    appId: '1:347814344271:android:f1552b40181964db6b1c3a',
    messagingSenderId: '347814344271',
    projectId: 'speechtotextapp-46ef3',
    storageBucket: 'speechtotextapp-46ef3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUO1P5sy9li585JoAhHWWhlEST8fbkiSQ',
    appId: '1:347814344271:ios:f59c788c5508076b6b1c3a',
    messagingSenderId: '347814344271',
    projectId: 'speechtotextapp-46ef3',
    storageBucket: 'speechtotextapp-46ef3.appspot.com',
    iosBundleId: 'com.example.audioToTextApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUO1P5sy9li585JoAhHWWhlEST8fbkiSQ',
    appId: '1:347814344271:ios:588414ca17e62fc76b1c3a',
    messagingSenderId: '347814344271',
    projectId: 'speechtotextapp-46ef3',
    storageBucket: 'speechtotextapp-46ef3.appspot.com',
    iosBundleId: 'com.example.audioToTextApp.RunnerTests',
  );
}
